best_model = {'model': 'RandomForestClassifier',
 'model__max_depth': 40,
 'model__min_samples_leaf': 1,
 'model__min_samples_split': 5,
 'model__n_estimators': 200}


columns_to_work = [
    # numeric
'HouseHoldID',
'HouseholdSize',
'TimeToOPD', 
'TimeToWater',
'AgricultureLand',
# categoric
'PerennialCropsGrown',
'hhh_read_write', 
'Material_walls',
'business_number', 
'work_casual', 
'work_salaried', 
'save_mode_7', 
'perennial_cropping', 
'latrine_constructed', 
"tippy_tap_available",  
'standard_hangline', 
'kitchen_house', 
'bathroom_constructed', 
'swept_compound', 
'dish_rack_present', 
'composts', 
'non_bio_waste_mgt_present', 
'apply_liquid_manure', 
'water_control_practise', 
'soil_management', 
'postharvest_food_storage',
'ProgressStatus'
]

best_numeric_columns = [
    'HouseholdSize',
    'TimeToOPD', 
    'TimeToWater',
    'AgricultureLand',
    'PerennialCropsGrown',
]

best_categoric_columns = [
'hhh_read_write', 
'Material_walls',
'business_number', 
'work_casual', 
'work_salaried', 
'save_mode_7', 
'perennial_cropping', 
'latrine_constructed', 
"tippy_tap_available",  
'standard_hangline', 
'kitchen_house', 
'bathroom_constructed', 
'swept_compound', 
'dish_rack_present', 
'composts', 
'non_bio_waste_mgt_present', 
'apply_liquid_manure', 
'water_control_practise', 
'soil_management', 
'postharvest_food_storage',
    ]

class_mappings = {

 'phones_owned': {'more_than_one': 0,
  'none': 1,
  'one': 2},

 'ProgressStatus': {'At Risk': 0,
  'On Track': 1,
  'Severely Struggling': 2,
  'Struggling': 3}}

categorical_columns = [
'District', 
'Cluster', 
'Village',  
'hhh_sex', 
'hhh_read_write', 
'Material_walls', 
'radios_owned', 
'phones_owned', 
'business_number', 
'work_casual', 
'work_salaried', 
'save_mode_7', 
'perennial_cropping', 
'daily_meals', 
'latrine_constructed', 
"tippy_tap_available", 
'soap_ash_available', 
'standard_hangline', 
'kitchen_house', 
'bathroom_constructed', 
'swept_compound', 
'dish_rack_present', 
'composts', 
'non_bio_waste_mgt_present', 
'apply_liquid_manure', 
'water_control_practise', 
'soil_management', 
'postharvest_food_storage',
'ProgressStatus'
]

numeric_columns = [
'HouseholdSize',
'TimeToOPD', 
'TimeToWater',
'AgricultureLand',
'VSLA_Profits',
'Season1VegetableIncome',
'Season2VegatableIncome',
'VegetableIncome',
'Season1VegetableValue',
'Season2VegetableValue',
'SeasonalVegetableValue',
'FormalEmployment',
'PersonalBusinessAndSelfEmployment',
'CasualLabour',
'RemittancesAndGifts',
'RentIncome',
'Season1CropIncome',
'Season2CropIncome',
'SeasonalCropIncome',
'PerenialCropIncome',
'LivestockIncome',
'Season1AgricValue',
'Season2AgricValue',
'SeasonalAgricValue',
'PerennialAgricValue',
'AgricValue',
'LivestockIncomeConsumed',
'LivestockAssetValue',
'HouseholdIcome',
'Consumption+Residues',
'HHIncome+Consumption+Residues',
'HHIncome+Consumption+Residues/Day',
'HHIncome+Consumption+Assets+Residues',
'HHIncome+Consumption+Assets+Residues/Day',
'Assets',
'PerennialCropsGrown'
]

